### ISSUE TITLE
2.6.0  does not have android-related artifacts

### ISSUE THREAD

**Issue by yshrsmz** [AAkira/Napier#105]
error log
```
* What went wrong:
Execution failed for task ':data:local:compileDebugKotlinAndroid'.
> Error while evaluating property 'filteredArgumentsMap' of task ':data:local:compileDebugKotlinAndroid'
   > Could not resolve all files for configuration ':data:local:debugCompileClasspath'.
      > Could not find io.github.aakira:napier-android-debug:2.6.0.
        Required by:
            project :data:local > io.github.aakira:napier:2.6.0
```

https://search.maven.org/artifact/io.github.aakira/napier-android
https://search.maven.org/artifact/io.github.aakira/napier-android-debug

**Comment by AAkira** [comment]
@yshrsmz 
Thank you for reporting.

I published Napier 2.6.1.
The android-debug artifact is [here](https://repo1.maven.org/maven2/io/github/aakira/napier-android-debug/2.6.1/).

Could you check it?

**Comment by yshrsmz** [comment]
👍 
Thanks, my CI is happy now!

**Comment by AAkira** [comment]
Thank you so much. 😄
