### ISSUE TITLE
How is this different from Kermit?

### ISSUE THREAD

**Issue by kaushalyap** [AAkira/Napier#107]
Kermit :  https://github.com/touchlab/Kermit

**Comment by chris-hatton** [comment]
Since Napier has been around a lot longer than Kermit, it may be more appropriate to ask _Kermit_ what they decided to do differently to Napier?

I think I can answer that though - Kermit saw an opportunity to make this much easier.  IMO Napier carries some confusing design decisions with it.

**Comment by kaushalyap** [comment]
Seem Kermit will be good choice since it is maintained by Touchlab who promotes Kotlin Multiplatform.
