### ISSUE TITLE
Failed to build with real iOS device

### ISSUE THREAD

**Issue by yshrsmz** [AAkira/Napier#15]
I got following error while building iOS app for real device.

```
w: skipping /Users/user/.gradle/caches/modules-2/files-2.1/com.github.aakira/napier-ios/0.0.4/aa6805b163ff862b63e862f4e63fa7852ca4d751/napier-ios-0.0.4.klib. The target doesn't match. Expected 'ios_arm64', found [ios_x64]
```

It looks like `napier-ios` artifact is for iOS simulator.

Please consider either of these;
- mention other iOS artifacts(`napier-iosArm34` and `napier-iosArm64`) in README and add how we should use these three
- make `napier-ios` ios common module, and let Gradle choose appropriate module depending on target iOS cpu architecture.

https://repo.maven.apache.org/maven2/com/squareup/sqldelight/ios-driver/1.1.3/
this link is the example of iOS common artifact.
As you can see, common module should include `*.module` file to choose appropriate artifact for different variants.

**Comment by AAkira** [comment]
Thank you for reporting!

I will try to make the ios common module on the next version.
Please specify the `napier-iosArm64` or `napier-iosArm32` in your gradle till then.

---

For other peoples

This is the artifacts list.
https://bintray.com/beta/#/aakira/maven/napier?tab=files

You should specify the `napier-iosArm64` or `napier-iosArm32` in your gradle if you want to use real iOS device.

```
iOSMain {
    dependencies {
        implementation 'com.github.aakira:napier-iosArm64:0.0.5'
    }
}
```

**Comment by JanStoltman** [comment]
@AAkira Is there any progress on this?

**Comment by yshrsmz** [comment]
My current workaround is something like this.

```gradle
def napier = [
  common  : "com.github.aakira:napier:${versions.napier}",
  android : "com.github.aakira:napier-android:${versions.napier}",
  iosX64  : "com.github.aakira:napier-ios:${versions.napier}",
  iosArm64: "com.github.aakira:napier-iosArm64:${versions.napier}",
]

kotlin {
  def iosTargetName = project.findProperty("kotlin.target") ?: "iosX64"
  def iosTarget = presets.getByName(iosTargetName)

  targetFromPreset(iosTarget) {
    binaries {
      framework()
    }
  }

  sourceSets {
    iosMain {
      dependencies {
        implementation napier[iosTargetName]
      }
    }
  }
}
```

**Comment by JanStoltman** [comment]
@yshrsmz Oh, that's clever 👍

**Comment by AAkira** [comment]
@yshrsmz @JanStoltman @wuseal

Hi guys!
I have good news.
I just published Napier 1.0.0.
It has the `napier-ios` artifact which includes Arm64, Arm32, and X64.
Please check it.

**Comment by yshrsmz** [comment]
That's great!
Thanks a lot 👍

**Comment by wuseal** [comment]
Great! Really Good News

**Comment by JanStoltman** [comment]
Nice, thanks!

**Comment by horita-yuya** [comment]
Amazing, thanks!!!!
