### ISSUE TITLE
Napier 0.0.5 is now compiled with 1.3.40, thus cannot be used with 1.3.31

### ISSUE THREAD

**Issue by yshrsmz** [AAkira/Napier#17]
Got following error while building iOS app.

```
: skipping /Users/vagrant/.gradle/caches/modules-2/files-2.1/com.github.aakira/napier-ios/0.0.5/a09fe8774ff1c9cc6c793a1414a756d25ab65299/napier-ios-0.0.5.klib. The abi versions don't match. Expected '[8]', found '9'

w: The compiler versions don't match either. Expected '[1.2.1]', found '1.3-release-10826'
```

https://bintray.com/aakira/maven/napier/0.0.5

As you can see version publication date of 0.0.5 is Jun 26, which is strange.

It looks like 0.0.5 was re-compiled with 1.3.40 and re-uploaded while releasing 0.0.6.
Could you re-upload 0.0.5 compiled with Kotlin 1.3.31?

**Comment by yshrsmz** [comment]
I suggest you to bump library version to non-stable version(such as `0.0.7-SNAPSHOT` as a post-release process.

**Comment by AAkira** [comment]
I'm so sorry.
I fixed it.
