### ISSUE TITLE
Add a way to remove Antilog

### ISSUE THREAD

**Issue by yshrsmz** [AAkira/Napier#18]
Like Timber's `Timber#uprootAll()`, it would be great if we have an option to remove already-added `Antilog`s.

In my case, if I try to use Napier in a Test and the test class has more than one test cases, `Napier.base()` is called multiple times, so same `Antilog` is added multiple times. Thus the same log is printed numerous times.

```kotlin
class LogTest {

  @BeforeTest
  fun setup() {
    // this is called once per a test case, so same Antilog is added multiple times.
	Napier.base(DebugAntilog())
  }

  @AfterTest
  fun tearDown() {
    // Napier.clearAntilog() // we need this!
  }

  @Test
  fun test1() {
    Napier.d("test1")
    // stdout:
    // test1
  }

  @Test
  fun test2() {
    Napier.d("test2")
    // stdout:
    // test2
    // test2
  }
}
```

**Comment by AAkira** [comment]
Thank you for your suggestion!
I added the function at Napier 0.0.7.

You can remove an antilog by calling `Napier.takeLogalitm()`.

**Comment by yshrsmz** [comment]
Thanks a lot for the quick update!

One quick question, Is `takeLogalitm` an intentional name? Quick googling suggests 'logarithm' instead of 'logaritm' 😄

**Comment by AAkira** [comment]
Yes, I noticed after I merged it.😂
Thank you for reporting.
I already overwrote.😅
