### ISSUE TITLE
Unresolved reference: Napier

### ISSUE THREAD

**Issue by gotamafandy** [AAkira/Napier#26]
hi, i'm getting `Unresolved reference: Napier` when trying to run this library. This is my gradle setup:

```
  sourceSets["commonMain"].dependencies {

        // Logging
        implementation("com.github.aakira:napier:${ extra.get("napierVersion") }")
    }
```

```
 sourceSets["androidMain"].dependencies {
       
        // Logging
        implementation("com.github.aakira:napier-android:${ extra.get("napierVersion") }")
    }
```

```
sourceSets["iosMain"].dependencies 

        // Logging
        implementation("com.github.aakira:napier-ios:${ extra.get("napierVersion") }")
    }
```

i can import and use this library with no error in IDE, but when trying to compile i get the error.

please help.

**Comment by AAkira** [comment]
I'm sorry. 
I have no idea.
I can use this library through jCenter.
You can download it from [here](https://bintray.com/aakira/maven/napier/1.0.0#files/com/github/aakira)

Do you have a sample project?

**Comment by gotamafandy** [comment]
hi Aakira, here's the example project:

https://www.dropbox.com/s/75oudosbg2qafcj/KotlinMPP.zip?dl=0

**Comment by AAkira** [comment]
@gotamafandy 

Do you have a gradle file in the root directory?
The gradle file in common directory looks good for me.

**Comment by gotamafandy** [comment]
hi @AAkira, no i don't have any build.gradle in root directory

**Comment by AAkira** [comment]
I think you should add a build.gradle in root directory.

I add the example of napier.
You can check here.

https://github.com/AAkira/mpp-example/tree/napier-example

**Comment by gotamafandy** [comment]
thanks i'll take a look. I'm going to close this issue now
