### ISSUE TITLE
Question. Pluggable loggers: slf4j, log4j2, luberjack, xcg, etc?

### ISSUE THREAD

**Issue by petrukhnov** [AAkira/Napier#27]
Is it possible to plug specific platform logger, so all output will be directed to it. 
E.g. push every log to slf4j on jvm and to xcg on ios?

**Comment by AAkira** [comment]
You can inject your logger like [DebugAntilog](https://github.com/AAkira/Napier/blob/master/napier/src/iosMain/kotlin/com/github/aakira/napier/DebugAntilog.kt).

You should implement the `Antilog` class in your class.
Then you inject it at first.

```kotlin
Napier.base(YourClass())
```

**Comment by petrukhnov** [comment]
thx!
