### ISSUE TITLE
Unresolved reference: Napier

### ISSUE THREAD

**Issue by pecanw** [AAkira/Napier#28]
I've got an issue when trying to use the Napier logging library in the kotlin mpp project. The symptoms are exactly the same as described in the [Issue 26](https://github.com/AAkira/Napier/issues/26) which has been closed.

To test the issue out of my project I have downloaded the [official Kotlin mpp example](https://github.com/Kotlin/mpp-example) and just upgraded the versions of gradle and kotlin and added the Napier library. You can find the project here:
[mpp-example.zip](https://github.com/AAkira/Napier/files/3846474/mpp-example.zip)

I'm getting the error `e: ...\mpp-example\greeting\src\commonMain\kotlin\common.kt: (3, 33): Unresolved reference: Napier`

**Comment by AAkira** [comment]
You should implement the napier platform plugin, Android or iOS or JVM or JS.

This problem is not faulted by this library.
Your gradle file is wrong.

* current 

```groovy
kotlin {
    targets {
        fromPreset(presets.android, 'androidLib')

        def buildForDevice = project.findProperty("device")?.toBoolean() ?: false
        def iosPreset = (buildForDevice) ? presets.iosArm64 : presets.iosX64
        fromPreset(iosPreset, 'ios') {
            binaries {
                framework {
                    // Disable bitcode embedding for the simulator build.
                    if (!buildForDevice) {
                        embedBitcode("disable")
                    }
                }
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation 'com.github.aakira:napier:1.0.0'
            }
        }
        commonTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test-common'
                implementation 'org.jetbrains.kotlin:kotlin-test-annotations-common'
            }
        }
        andriodTest {
            dependencies {
                implementation 'com.github.aakira:napier-android:1.0.0'
            }
        }
    }
}
```
* after

```
        andriodLibMain {
            dependencies {
                implementation 'com.github.aakira:napier-android:1.0.0'
            }
        }
```
