### ISSUE TITLE
Kotlin 1.3.70 Support

### ISSUE THREAD

**Issue by oktinaut** [AAkira/Napier#32]
A new build is needed for Native Support on Kotlin 1.3.70.

**Comment by AAkira** [comment]
https://github.com/AAkira/Napier/tree/kotlin/1.3.70 is in progress.

I have waited for the release of kotlinx.coroutines.
I'll do it.

**Comment by AAkira** [comment]
@oktinaut 
I'm sorry for the wait.
I just released the 1.2.0.
