### ISSUE TITLE
Macos target

### ISSUE THREAD

**Issue by terrakok** [AAkira/Napier#40]
Hello! Have you any plans about native (macosX64 and others) target support?

**Comment by AAkira** [comment]
Hello!
At the moment, I don't intend to add these artifacts.
I'll do it if you want.
Do you need only the macosX64?

**Comment by agent10** [comment]
+ tvOS

**Comment by Sebulec** [comment]
@AAkira Hello, I would also like to use this library in tvOS target. Are you able to add it?

**Comment by jstarczewski** [comment]
@AAkira I would like to use it on tvOS target too :)

**Comment by AAkira** [comment]
Please check `2.0.0-alpha2`
