### ISSUE TITLE
Could not find com.github.aakira:napier-ios:1.4.0.

### ISSUE THREAD

**Issue by schmidt9** [AAkira/Napier#47]
Error when using version 1.4.0
> Could not resolve com.github.aakira:napier-ios:1.4.0
```
iosMain {
            dependencies {
                implementation "com.github.aakira:napier-ios:$napierVersion"
            }
        }
```

**Comment by AAkira** [comment]
Thank you for reporting.
I see...

I changed the .module file in ios directory on 1.4.0.
I think you don't need to set `com.github.aakira:napier-ios`.

You can write the implementation line only once from Kotlin 1.4.0.

```
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation 'com.github.aakira:napier:1.4.0'
            }
        }
    }
}
```

Cf.
https://kotlinlang.org/docs/reference/whatsnew14.html#specifying-dependencies-only-once

Do you need `napier-ios` module?

**Comment by schmidt9** [comment]
In works now on Android and iOS with `commonMain` dependency indeed. Thanks
