### ISSUE TITLE
Logging from another thread on iOS

### ISSUE THREAD

**Issue by soniccat** [AAkira/Napier#56]
Hi. 
I've tried to call Napier.v on iOS inside of withContext(Dispatchers.Default) i.e. from a non-main thread and didn't get anything logged.
I see you use ThreadLocal annotation for Napier. And it seems on iOS I need to initialize Napier separately for Dispatchers.Default thread. Probably it worth adding support for logging from a non-main thread by default as now it looks like a bug.

In this example, I see only the first message logged on iOS. But the both messages are logged on Android. If I add Napier initialization inside of Dispatchers.Default, the both messages will be logged on iOS too:
```
suspend fun loadDefinition(word: String): OwlBotWord {
        Napier.v("Loading definition for: $word", tag = TAG)

        val res: HttpResponse = httpClient.get("${baseUrl}api/v4/dictionary/${word}")
        return withContext(Dispatchers.Default) {
            // If I initialize Napper here the second message will be logged
            val response = res.readBytes().decodeToString()
            if (res.status == HttpStatusCode.OK) {
                Napier.v("Loded definition for: $word", tag = TAG)
            } else {
                Napier.e("Status: ${res.status} response: $response", tag = TAG)
            }
            Json {
                ignoreUnknownKeys = true
            }.decodeFromString(response)
        }
    }
```

For now I've ended up with calling this on iOS in a setup function:
```
    private val defaultScope = CoroutineScope(Dispatchers.Default + SupervisorJob())

    actual fun setupDebug() {
        Napier.base(DebugAntilog())

        defaultScope.launch {
            Napier.base(DebugAntilog())
        }
    }
```

**Comment by RomeuG** [comment]
Any news on this?

**Comment by PhilipDukhov** [comment]
@RomeuG you can check out my [solution](https://github.com/PhilipDukhov/Napier). Not sure if the maintainer is available.

**Comment by RomeuG** [comment]
Thanks, I guess Napier itself is dead.

**Comment by SorrowBlue** [comment]
@RomeuG @PhilipDukhov 
I contacted the maintainer on Twitter. He has plans to respond after May. Because he is busy now.

**Comment by AAkira** [comment]
Please check `2.0.0-alpha2`
