### ISSUE TITLE
Output not coloured under Android

### ISSUE THREAD

**Issue by ln-12** [AAkira/Napier#58]
As shown in the following image, the output is not coloured. What am I doing wrong?

![image](https://user-images.githubusercontent.com/36760115/100749399-e86dc480-33e4-11eb-878a-a43d043448cc.png)

**Comment by micHar** [comment]
The coloring is on the Android Studio side, not the Napier lib. Napier can only provide logging level. If you do `Napier.e` then you will have red color with the default AS settings.

**Comment by ln-12** [comment]
Got it working now, thanks!
