### ISSUE TITLE
Double logging on Android LogCat makes Napier unusable

### ISSUE THREAD

**Issue by chris-hatton** [AAkira/Napier#63]
For some reason, every Napier log in Androids LogCat is duplicated with these tags:
```
W/System.err <message>
I/DebugAntilog <message>
```
The double logging makes log output unreadable to the point I no longer want to use Napier.
Are others experiencing this issue; and is there an easy resolution?

`I/DebugAntilog` is expected; I can't see why `W/System.err` is being logged:
This is for all log levels, not just warnings or errors.

iOS logging is working as expected.

**Comment by christianaye** [comment]
it is a common java problem. there are two loggers registered. AntilogDebug add a new logger with default console handler to existing parent logger.
you can change this behavior with following Kotlin code:

```
Napier.base(DebugAntilog("app", listOf(ConsoleHandler().apply {
    level = Level.INFO
    formatter = SimpleFormatter()
}))) // optional
val antilogLogger = Logger.getLogger(DebugAntilog::class.java.name)
antilogLogger.useParentHandlers = false
```
see last line. you have to set setUseParentHandlers to false [see here](https://stackoverflow.com/a/44526490)

i think this should be documented in this project

**Comment by chris-hatton** [comment]
Weird design decision that one would need to write that boilerplate just to get sane logging on Android.
Logging should be easy, and libraries should deliver value.  I can see that trying to use Napier was a waste of time.
