### ISSUE TITLE
warning 

### ISSUE THREAD

**Issue by anuj72** [AAkira/Napier#67]
![Screenshot 2021-05-26 at 4 24 33 PM](https://user-images.githubusercontent.com/26837182/119648359-fdc92600-be3e-11eb-8dee-33d9dabea383.png)

i am getting a warning  to remove jcenter()  in am developing app in kotlin kmm but i remove jcenter() the libary doesnot work.

**Comment by AAkira** [comment]
You can download from `io.github.aakira:napier:x.y.z`.
