### ISSUE TITLE
Can not find version: napier-iosarm64-2.1.0-samplessources.jar 

### ISSUE THREAD

**Issue by MartinWong-H** [AAkira/Napier#89]
buildscript {
  repositories {
    google()
    mavenCentral ()
}

org.gradle.internal.resolve.ArtifactNotFoundException: Could not find napier-iosarm64-2.1.0-samplessources.jar (io.github.aakira:napier-iosarm64:2.1.0).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/io/github/aakira/napier-iosarm64/2.1.0/napier-iosarm64

**Comment by AAkira** [comment]
I don't think this is Napier's problem.

cf.
https://youtrack.jetbrains.com/issue/KTIJ-10769

The correct link is this.
https://repo.maven.apache.org/maven2/io/github/aakira/napier-iosarm64/2.1.0/

**Comment by MartinWong-H** [comment]
let me try  thx!
