### ISSUE TITLE
Handling Swift exceptions

### ISSUE THREAD

**Issue by akoshkidko** [AAkira/Napier#99]
Hello @AAkira 

I develop KMM app and want to use Napier both for Android and iOS.

According to Napier [README.md](https://github.com/AAkira/Napier#readme) we can handle errors in Kotlin code like that
```
fun handleError() {
    try {
            throw Exception("throw error")
        } catch (e: Exception) {
            Napier.e("Napier Error", e)
    }
}

```
   
   Is is possible to handle `Error` /  `NSError` in a similar way in Swift code? May be another way to handle exceptions in iOS app?

**Comment by AAkira** [comment]
You should check here.
I recommend Kotlin lang slack to ask questions for KMM.

https://kotlinlang.org/docs/native-objc-interop.html#mappings
